spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jdbctest
    username: root
    password: awwaqe
    driver-class-name: com.mysql.cj.jdbc.Driver

